AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template using mod1 and mod2 as modules

Resources:
  Mod1:
    # if we wanted to use Rain modules we would use the following line instead of the one below
    # it will also need adddition of -x flag to the pkg command
    # Type: !Rain::Module "./mod1.yaml"
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: ./mod1.yaml

  Mod2:
    # Type: !Rain::Module "./mod2.yaml"
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./mod2.yaml

