AWSTemplateFormatVersion: 2010-09-09
Description: Create an Python lambda function

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  PyLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: PyLambdaLayer
      Description: Python Lambda layer for pyjokes
      Content: ../py-lambda/package
      CompatibleRuntimes:
        - python3.12

  PyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../py-lambda/src
      FunctionName: PyLambdaFunction
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.12
      Layers:
        - !Ref PyLambdaLayer

Outputs:
  LambdaFunctionArn:
    Description: The ARN of the Lambda function
    Value: !GetAtt PyLambdaFunction.Arn
